/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysoftware;


import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SiD
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        student = new javax.swing.JFrame();
        faculty = new javax.swing.JFrame();
        admin = new javax.swing.JFrame();
        addbook = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        baa = new javax.swing.JLabel();
        abc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        abd = new javax.swing.JTextArea();
        abq = new javax.swing.JTextField();
        abl = new javax.swing.JTextField();
        aba = new javax.swing.JTextField();
        aby = new javax.swing.JTextField();
        abp = new javax.swing.JTextField();
        abn = new javax.swing.JTextField();
        abi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        issuebook = new javax.swing.JFrame();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        isla = new javax.swing.JLabel();
        isf = new javax.swing.JRadioButton();
        iss = new javax.swing.JRadioButton();
        yi = new javax.swing.JComboBox<>();
        mi = new javax.swing.JComboBox<>();
        di = new javax.swing.JComboBox<>();
        iid = new javax.swing.JTextField();
        rmn = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        returnbook = new javax.swing.JFrame();
        retbutton = new javax.swing.JButton();
        rf = new javax.swing.JRadioButton();
        rs = new javax.swing.JRadioButton();
        rbi = new javax.swing.JTextField();
        rrn = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lbq = new javax.swing.JLabel();
        rb5 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        loginpagel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        su4 = new javax.swing.JTextField();
        su3 = new javax.swing.JTextField();
        su2 = new javax.swing.JTextField();
        su1 = new javax.swing.JTextField();
        usn = new javax.swing.JTextField();
        psn = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sucb1 = new javax.swing.JComboBox<>();
        sucb2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        signupl2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signupl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pl = new javax.swing.JLabel();
        sur = new javax.swing.JPasswordField();
        sup = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        student.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faculty.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addbook.setMinimumSize(new java.awt.Dimension(1920, 1080));
        addbook.setResizable(false);
        addbook.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addbookMouseMoved(evt);
            }
        });
        addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbookMouseClicked(evt);
            }
        });
        addbook.addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                addbookWindowStateChanged(evt);
            }
        });
        addbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addbookKeyPressed(evt);
            }
        });
        addbook.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(203, 45, 29));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        addbook.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 410, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Quantity");
        addbook.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Location");
        addbook.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Year");
        addbook.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Author");
        addbook.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Publisher");
        addbook.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Category");
        addbook.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Description");
        addbook.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/adpn.png"))); // NOI18N
        jLabel12.setText("Add Book");
        addbook.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 170));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Book Name");
        addbook.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Book id");
        addbook.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        baa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addbook.getContentPane().add(baa, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 240, 40));

        abc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        abc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer science, information and general works", "Philosophy and psychology", "Religion", "Social Sciences", "Language", "Science", "Technology and applied science", "Arts and recreation", "Literature", "History and geography", " " }));
        abc.setSelectedIndex(10);
        addbook.getContentPane().add(abc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 510, -1));

        abd.setColumns(20);
        abd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        abd.setRows(5);
        jScrollPane1.setViewportView(abd);

        addbook.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 510, -1));

        abq.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        abq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abqActionPerformed(evt);
            }
        });
        addbook.getContentPane().add(abq, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 510, -1));

        abl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbook.getContentPane().add(abl, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 510, -1));

        aba.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbook.getContentPane().add(aba, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, 510, -1));

        aby.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbook.getContentPane().add(aby, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 510, -1));

        abp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbook.getContentPane().add(abp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 510, -1));

        abn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbook.getContentPane().add(abn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 510, -1));

        abi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbook.getContentPane().add(abi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 510, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/addbook.jpg"))); // NOI18N
        addbook.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -80, 1930, 1330));

        issuebook.setMinimumSize(new java.awt.Dimension(1930, 1080));
        issuebook.setResizable(false);
        issuebook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                issuebookFocusGained(evt);
            }
        });
        issuebook.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                issuebookWindowActivated(evt);
            }
        });
        issuebook.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Date");
        issuebook.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel23.setText("Issue Book");
        issuebook.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("Book id");
        issuebook.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        isla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isla.setText("Registration No.");
        issuebook.getContentPane().add(isla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        buttonGroup3.add(isf);
        isf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isf.setText("Faculty");
        isf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isfActionPerformed(evt);
            }
        });
        issuebook.getContentPane().add(isf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        buttonGroup3.add(iss);
        iss.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        iss.setSelected(true);
        iss.setText("Student");
        iss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issActionPerformed(evt);
            }
        });
        issuebook.getContentPane().add(iss, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        yi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        yi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        issuebook.getContentPane().add(yi, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 430, 150, -1));

        mi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        issuebook.getContentPane().add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 120, -1));

        di.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        di.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        issuebook.getContentPane().add(di, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 100, -1));

        iid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        issuebook.getContentPane().add(iid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 400, -1));

        rmn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        issuebook.getContentPane().add(rmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 400, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("Issue");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        issuebook.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 290, 60));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/bookissue.jpg"))); // NOI18N
        issuebook.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, 1080));

        returnbook.setMinimumSize(new java.awt.Dimension(1930, 1080));
        returnbook.setResizable(false);
        returnbook.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retbutton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        retbutton.setText("Return");
        retbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retbuttonActionPerformed(evt);
            }
        });
        returnbook.getContentPane().add(retbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 330, 60));

        buttonGroup4.add(rf);
        rf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rf.setText("Faculty");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });
        returnbook.getContentPane().add(rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 130, -1));

        buttonGroup4.add(rs);
        rs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rs.setSelected(true);
        rs.setText("Student");
        rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsActionPerformed(evt);
            }
        });
        returnbook.getContentPane().add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 140, -1));

        rbi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        returnbook.getContentPane().add(rbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 490, -1));

        rrn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        returnbook.getContentPane().add(rrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 490, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setText("Return Book");
        returnbook.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("Book id");
        returnbook.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        rel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rel.setText("Registration No.");
        returnbook.getContentPane().add(rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/bookret.jpg"))); // NOI18N
        jLabel24.setMinimumSize(new java.awt.Dimension(1930, 1201));
        returnbook.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/b1.jpg"))); // NOI18N
        getContentPane().add(lbq, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 890, 730));

        buttonGroup1.add(rb5);
        rb5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb5.setText("Administrator");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });
        getContentPane().add(rb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1333, 160, 140, -1));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb1.setSelected(true);
        rb1.setText("Student");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, -1, -1));

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb2.setText("Faculty");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 160, -1, -1));

        buttonGroup2.add(rb3);
        rb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb3.setSelected(true);
        rb3.setText("Student");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 630, -1, -1));

        buttonGroup2.add(rb4);
        rb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb4.setText("Faculty");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });
        getContentPane().add(rb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 670, 110, -1));

        loginpagel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginpagel1.setText("Registration No.");
        getContentPane().add(loginpagel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 80, -1, -1));

        su4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(su4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 490, 370, -1));

        su3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(su3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 490, 310, -1));

        su2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(su2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 720, -1));

        su1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(su1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 720, -1));

        usn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usnActionPerformed(evt);
            }
        });
        getContentPane().add(usn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, 250, 40));

        psn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(psn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 110, 250, 40));

        jButton4.setText("Bam");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 80, 70));

        jButton2.setText("Boom");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 80, 70));

        jButton1.setBackground(new java.awt.Color(70, 85, 240));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 110, 150, -1));

        sucb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sucb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        getContentPane().add(sucb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 560, 310, -1));

        sucb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sucb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech.", "M.Tech.", "MCA", "BBA" }));
        getContentPane().add(sucb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 560, 370, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("E-Mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 460, -1, -1));

        signupl2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        signupl2.setText("Name");
        getContentPane().add(signupl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Re-Enter Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 740, -1, -1));

        signupl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        signupl1.setText("Registration Number");
        getContentPane().add(signupl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 740, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Sign-Up");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, -1, -1));

        pl.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 810, 150, 20));

        sur.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                surKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                surKeyReleased(evt);
            }
        });
        getContentPane().add(sur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 770, 360, -1));

        sup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 770, 320, -1));

        jButton6.setText("Bang");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 80, 70));

        signup.setBackground(new java.awt.Color(27, 146, 229));
        signup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(240, 240, 240));
        signup.setText("Sign-Up");
        signup.setEnabled(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 860, 720, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Software");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Management");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/logo (1).png"))); // NOI18N
        jLabel4.setText("Library");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 450, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysoftware/images/274487.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1930, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usnActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

   

        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 String[] images={"b1.jpg","b2.jpg","b3.jpg","b4.jpg","b5.jpg","b6.jpg"}; 
    Random x = new Random();
int n = x.nextInt(6);
       ImageIcon iic= new ImageIcon(getClass().getResource("/librarysoftware/images/quotes/"+images[n]));
       lbq.setIcon(iic);    
       
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
loginpagel1.setText("Member ID");
usn.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
loginpagel1.setText("Registration No."); 
usn.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
signupl1.setText("Registration Number");  
sucb1.setEnabled(true);   
sucb2.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
signupl1.setText("Member ID");   
sucb1.setEnabled(false);   
sucb2.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
try
{
Class.forName("java.sql.DriverManager");
Connection con=(Connection)(DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","root"));
Statement sp=con.createStatement();
String q,a,b,c,d,e,f,p;
int y=1;
    a=su1.getText();
    b=su2.getText();
    c=su3.getText();
    d=su4.getText();
    e=(String) sucb1.getSelectedItem();
   if(e.equals("1st Year"))
   {
       y=1;
   }
   else if(e.equals("2nd Year"))
   {
       y=2;
   }
   else if(e.equals("3rd Year"))
   {
       y=3;
   }
   else if(e.equals("4th Year"))
   {
       y=4;
   }
   
    f=(String) sucb2.getSelectedItem();
    p= new String(sup.getPassword());
if(rb3.isSelected()==true)
{
    q="insert into students(regno,name,phno,branch,year,email,password) values('"+a+"','"+b+"','"+c+"','"+f+"',"+y+",'"+d+"','"+p+"')"; 
   sp.executeUpdate(q);
}
else
{
    q="insert into teachers(memno,name,phno,email,password) values('"+a+"','"+b+"','"+c+"','"+d+"','"+p+"')";
    sp.executeUpdate(q);
}


usn.setText(a);
psn.setText(p);

    su1.setText("");
    su2.setText("");
    su3.setText("");
    su4.setText("");
    sup.setText("");
    sur.setText("");
    signup.setEnabled(false);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Write Correctly Please...");
    pl.setText("");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void surKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surKeyPressed

 

        // TODO add your handling code here:
    }//GEN-LAST:event_surKeyPressed

    private void surKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surKeyReleased
String p,rp;
 p= new String(sup.getPassword());
 rp=new String(sur.getPassword());
 if(p.equals(rp))
 {
     signup.setEnabled(true);
     pl.setText("");
 }
 else 
 {
     signup.setEnabled(false);
     pl.setText("Password not matching");
 }
// TODO add your handling code here:
    }//GEN-LAST:event_surKeyReleased

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
loginpagel1.setText("");
usn.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
addbook.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void abqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abqActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
{
Class.forName("java.sql.DriverManager");
Connection con=(Connection)(DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","root"));
Statement sp=con.createStatement();
String q,a,b,c,d,e,f,g,h,p,y;
    a=abi.getText();
    b=abn.getText();
    c=abd.getText();
    d=(String) abc.getSelectedItem();
    e=abp.getText();
    f=aba.getText();
    y=aby.getText();
    g=abl.getText();
    h=abq.getText();
    q="insert into books(bookid ,name,descr,cat,publisher,author,year,location,qtyav) values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"',"+y+",'"+g+"',"+h+")"; 

sp.executeUpdate(q);

   baa.setText("Book Added");
    abi.setText("");
    abn.setText("");
    abd.setText("");
    abp.setText("");
    aba.setText("");
    aby.setText("");
    abl.setText("");
    abq.setText("");
    abc.setSelectedIndex(10);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Write Correctly Please...");
    abi.setText("");
    abn.setText("");
    abd.setText("");
    abp.setText("");
    aba.setText("");
    aby.setText("");
    abl.setText("");
    abq.setText("");
    abc.setSelectedIndex(10);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addbookWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addbookWindowStateChanged
    // TODO add your handling code
    }//GEN-LAST:event_addbookWindowStateChanged

    private void addbookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addbookKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_addbookKeyPressed

    private void addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseClicked
  // baa.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_addbookMouseClicked

    private void addbookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseMoved
        baa.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_addbookMouseMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
issuebook.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void isfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isfActionPerformed
isla.setText("Member ID");
        // TODO add your handling code here:
    }//GEN-LAST:event_isfActionPerformed

    private void issuebookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issuebookFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_issuebookFocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try
{
Class.forName("java.sql.DriverManager");
Connection con=(Connection)(DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","root"));
Statement sp1=con.createStatement();
Statement sp2=con.createStatement();
Statement sp3=con.createStatement();
Statement sp4=con.createStatement();
String a,b,q1,q2,q3,q4,d,m,y;
int in,qa,qi;
a=rmn.getText();
b=iid.getText();
d=(String)di.getSelectedItem();
m= Integer.toString(mi.getSelectedIndex()+1);
y=(String)yi.getSelectedItem();


q2="select * from books where bookid= '"+b+"'";
ResultSet rs2=sp2.executeQuery(q2);
if(iss.isSelected()==true)
{
    q1="select * from students where regno ='"+a+"'";
    ResultSet rs1=sp1.executeQuery(q1);
     
    if (rs1.next()==true && rs2.next()==true)
        {
            qa=Integer.parseInt(rs2.getString("qtyav"));
            qi=Integer.parseInt(rs2.getString("qtyis"));
            in=Integer.parseInt(rs1.getString("issueno"));
            if(in<3 && qa!=0)
            {
                in++;
            q3="update students set book"+in+" = '"+b+"', b"+in+"ret= '"+y+"-"+m+"-"+d+"',issueno= "+in+"  where regno= '"+a+"'";
            sp3.executeUpdate(q3);
            qa--;
            qi++;
            q4="update books set qtyav= "+qa+",qtyis= "+qi+" where bookid= '"+b+"'";
            sp4.executeUpdate(q4);
            }
        }
    
    else
    {
        JOptionPane.showMessageDialog(null, "Book ID or Reg no. Wrong...");
    }
}
else if(isf.isSelected()==true)
{
    q1="select * from teachers where memno ='"+a+"'";
    ResultSet rs1=sp1.executeQuery(q1);
     
    if (rs1.next()==true && rs2.next()==true)
        {
            qa=Integer.parseInt(rs2.getString("qtyav"));
            qi=Integer.parseInt(rs2.getString("qtyis"));
            in=Integer.parseInt(rs1.getString("issueno"));
            if(in<3 && qa!=0)
            {
                in++;
            q3="update teachers set book"+in+"= '"+b+"',issueno="+in+" where memno= '"+a+"'";
            sp3.executeUpdate(q3);
            qa--;
            qi++;
            q4="update books set qtyav= "+qa+",qtyis= "+qi+" where bookid= '"+b+"'";
            sp4.executeUpdate(q4);
            }
        }
    
    else
    {
        JOptionPane.showMessageDialog(null, "Book ID or Member ID Wrong...");
    }
    
 
    
}
   rmn.setText("");
   iid.setText("");

}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
 
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void issuebookWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_issuebookWindowActivated
Calendar lCal = Calendar.getInstance();
int lYear = lCal.get(Calendar.YEAR)%50;
int lMonth = lCal.get(Calendar.MONTH)+1;
int lDay = lCal.get(Calendar.DATE);
    di.setSelectedIndex(lDay-1);
    mi.setSelectedIndex(lMonth-1);
    yi.setSelectedIndex(lYear);        // TODO add your handling code here:
    }//GEN-LAST:event_issuebookWindowActivated

    private void issActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issActionPerformed
isla.setText("Registration No.");        // TODO add your handling code here:
    }//GEN-LAST:event_issActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
returnbook.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void rsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsActionPerformed
rel.setText("Registraton No.");        // TODO add your handling code here:
    }//GEN-LAST:event_rsActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
rel.setText("Member ID");        // TODO add your handling code here:
    }//GEN-LAST:event_rfActionPerformed

    private void retbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retbuttonActionPerformed
try
{
Class.forName("java.sql.DriverManager");
Connection con=(Connection)(DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","root"));
Statement sp1=con.createStatement();
Statement sp2=con.createStatement();
Statement sp3=con.createStatement();
Statement sp4=con.createStatement();
Statement sp5=con.createStatement();
Statement sp6=con.createStatement();
String q1,q2,q3,q4,q5,q6,b1,b2,b3,b1r,b2r,b3r;
int isn,qtya,qtyi;
String ri,rb;
ri=rrn.getText();
rb=rbi.getText();
q5="select * from books where bookid= '"+rb+"'";
JOptionPane.showMessageDialog(null, q5);
ResultSet rsb=sp5.executeQuery(q5);
rsb.next();
qtya=Integer.parseInt(rsb.getString("qtyav"));
qtyi=Integer.parseInt(rsb.getString("qtyis"));  


if(rs.isSelected()==true)
{
    q1="select * from students where (book1= '"+rb+"' or book2= '"+rb+"' or book3= '"+rb+"' ) and regno= '"+ri+"'";
    ResultSet rs1= sp1.executeQuery(q1);
    rs1.next();
    isn= Integer.parseInt(rs1.getString("issueno"));
    b1= rs1.getString("book1");
    b2= rs1.getString("book2");
    b3= rs1.getString("book3");
    
    b1r= rs1.getString("b1ret");
    b2r= rs1.getString("b2ret");
    b3r= rs1.getString("b3ret");
    
    
    if(isn==0)
    {
        JOptionPane.showMessageDialog(null, "No book issued");
    }
    
    else if(isn==1)
    {
        if(b1.equals(rb)==true)
        {
         q2="update students set book1= NULL, b1ret= NULL, issueno= 0";
         qtya++;
         qtyi--;
         q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+" where bookid= '"+rb+"'";
         
         sp2.executeUpdate(q2);
         sp6.executeUpdate(q6);
        }
    }
    
    else if(isn==2)
    {
        if(b2.equals(rb)==true)
        {
            q2="update students set book2= NULL, b2ret= NULL, issueno= 1";
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+" where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
             
        }
        else
        {
            q2="update students set book1='"+b2+"', b1ret="+b2r+", issueno= 1";
            q3="update students set book2= NULL, b2ret= NULL";
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+" where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            
            sp2.executeUpdate(q2);
            sp3.executeUpdate(q3);
            
        }
    }
    
    else if(isn==3)
    {
        if(b3.equals(rb)==true)
        {
            q2="update students set book3= NULL, b3ret= NULL, issueno= 2";
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+" where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            
        }
        else if(b2.equals(rb)==true)
        {
            q2="update students set book2='"+b3+"', b2ret="+b3r+", issueno= 2";
            q3="update students set book3= NULL, b3ret= NULL";
            
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+" where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            sp3.executeUpdate(q3);
               
        }
        else
        {
            q2="update students set book1='"+b2+"', b1ret="+b2r+", issueno= 2";
            q3="update students set book2='"+b3+"', b2ret="+b3r;
            q4="update students set book3= NULL, b3ret= NULL";
            
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+" where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            sp3.executeUpdate(q3);
            sp4.executeUpdate(q4);
            
        }
    }
    
}
else
{
    q1="select * from teachers where (book1= '"+rb+"' or book2= '"+rb+"' or book3= '"+rb+"') and memno= '"+ri+"'";
    ResultSet rs1= sp1.executeQuery(q1);
    isn= Integer.parseInt(rs1.getString("issueno"));
    b1= rs1.getString("book1");
    b2= rs1.getString("book2");
    b3= rs1.getString("book3");
    
    
    if(isn==0)
    {
        JOptionPane.showMessageDialog(null, "No book issued");
    }
    
    else if(isn==1)
    {
         q2="update teachers set book1= NULL, issueno= 0";
         qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+"where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
    }
    
    else if(isn==2)
    {
        if(b2.equals(rb)==true)
        {
            q2="update teachers set book2= NULL, issueno= 1";
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+"where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            
        }
        else
        {
            q2="update teachers set book1='"+b2+"', issueno= 1";
            q3="update teachers set book2= NULL";
            
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+"where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            sp3.executeUpdate(q3);
            
        }
    }
    
    else if(isn==3)
    {
        if(b3.equals(rb)==true)
        {
            q2="update teachers set book3= NULL, issueno= 2";
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+"where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            
        }
        else if(b2.equals(rb)==true)
        {
            q2="update teachers set book2='"+b3+"', issueno= 2";
            q3="update teachers set book3= NULL";
            
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+"where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            sp3.executeUpdate(q3);
               
        }
        else
        {
            q2="update teachers set book1='"+b2+"', issueno= 2";
            q3="update teachers set book2='"+b3;
            q4="update teachers set book3= NULL";
            
            qtya++;
            qtyi--;
            q6="update books set qtyav= "+qtya+", qtyis= "+qtyi+"where bookid= '"+rb+"'";
         
            sp6.executeUpdate(q6);
            sp2.executeUpdate(q2);
            sp3.executeUpdate(q3);
            sp4.executeUpdate(q4);
            
        }
    }
    
}

}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_retbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aba;
    private javax.swing.JComboBox<String> abc;
    private javax.swing.JTextArea abd;
    private javax.swing.JTextField abi;
    private javax.swing.JTextField abl;
    private javax.swing.JTextField abn;
    private javax.swing.JTextField abp;
    private javax.swing.JTextField abq;
    private javax.swing.JTextField aby;
    private javax.swing.JFrame addbook;
    private javax.swing.JFrame admin;
    private javax.swing.JLabel baa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> di;
    private javax.swing.JFrame faculty;
    private javax.swing.JTextField iid;
    private javax.swing.JRadioButton isf;
    private javax.swing.JLabel isla;
    private javax.swing.JRadioButton iss;
    private javax.swing.JFrame issuebook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbq;
    private javax.swing.JLabel loginpagel1;
    private javax.swing.JComboBox<String> mi;
    private javax.swing.JLabel pl;
    private javax.swing.JPasswordField psn;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JTextField rbi;
    private javax.swing.JLabel rel;
    private javax.swing.JButton retbutton;
    private javax.swing.JFrame returnbook;
    private javax.swing.JRadioButton rf;
    private javax.swing.JTextField rmn;
    private javax.swing.JTextField rrn;
    private javax.swing.JRadioButton rs;
    private javax.swing.JButton signup;
    private javax.swing.JLabel signupl1;
    private javax.swing.JLabel signupl2;
    private javax.swing.JFrame student;
    private javax.swing.JTextField su1;
    private javax.swing.JTextField su2;
    private javax.swing.JTextField su3;
    private javax.swing.JTextField su4;
    private javax.swing.JComboBox<String> sucb1;
    private javax.swing.JComboBox<String> sucb2;
    private javax.swing.JPasswordField sup;
    private javax.swing.JPasswordField sur;
    private javax.swing.JTextField usn;
    private javax.swing.JComboBox<String> yi;
    // End of variables declaration//GEN-END:variables

    private ImageIcon ImageIcon(String cUsersSiDDocumentsNetBeansProjectsLibrary) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String String(char[] password) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
